# Introducción a Julia - Parte 1

Julia lo puedes descargar desde https://julialang.org

La versión más estable es la v1.5.3.

## ¿Realmente necesitamos aprender otro lenguaje?

El problema de los dos lenguajes.

En primer lugar, al elegir un lenguaje se considera la facilidad de aprendizaje, la generación de código rápidamente, esto es la **productividad** (_productive_ o _high-level languages_) que ofrece el lenguaje: python, ruby, matlab
En segundo lugar, en diversos problemas a tratar es indispensable considerar  el **rendimiento** del lenguaje de programación (_performance_ o _lower-level languages_) y la generación del código máquina eficiente: Fortran, C, C++. En general un lenguaje es atractivo si es productivo, sin embargo su rendimiento no es óptimo y viceversa; por tanto, la elección de productividad o rendimiento dependerá de las necesidades particulares del problema a resolver.

Adicional a lo anterior la **generalidad** del lenguaje, esto es tomar en cuenta si se trata de un lenguaje de propósito genenal (_general purpose language_) o de dominio específico (_domain-specific language_). Es posible generar código eficiente y rápido de manera sencilla si se trabaja cn lenguajes de dominio específico o con librerías especiales sin embargo el alcance (_scope_) de dichas herramientas será un tanto limitado.

Así, para lograr la productividad, rendimiento y generalidad ( _Productivity vs Performance vs Generality_) es necesario utilizar dos lenguajes. El prototipado de las soluciones se realiza por medio de un lenguaje de alto nivel como Python o MATLAB lo que proporciona una prueba de concepto rápidamente; una vez hecho lo anterior, se realiza la traducción del protototipo a otro lenguaje como C o C++ para realizar los cálculos de manera eficiente.

Evitar el uso de dos lenguajes de programación es la razón primordial de Julia.


El lema de Julia es:

> "looks like **Python**, feels like **Lisp**, runs like **C**"

lo cual puede entenderse en el sentido que Julia ofrece productividad, generalidad y **rendimiento**.

### ¿Por qué elegí Julia para este curso?

### Ventajas de Julia

- Es interpretado
- Es un lenguaje de alto nivel, fácil de aprender
- Diseñado para que sea sencillo desde el comienzo
- Es veloz (~2-3 x la velocidad de C)
- Tiene un sofisticado sistema de tipos de datos
- Sin embargo no es necesario hablar de tipos siempre
- Tiene _despacho múltiple_ de funciones especializado en el tipo de sus argumentos
- Tiene un sofisticado empleo de _metaprogramación_(macros) para la generación de código
- La mayoría de las bibliotecas están implementadas en Julia puro
- Evita el problema del segundo lenguaje: Python, R, Matlab son fáciles de aprender y se logran desarrollos rápidos, sin embargo tienen ejeccuicones lentas, entonces es necesario cambiar ciertas partes del código a C, C++ o Fortran
- Los propios usuarios de Julia son sus desarrolladores

## Recursos

* Discourse: https://discourse.julialang.org Grupo de discusión sobre Julia
* Github: https://github.com/JuliaLang/julia Código puro
* JuliaWebPage: https://julialang.org/learning/ Recursos variados: tutoriales en video y escritos, libros, MOOCS, clases de cómputo cientifico con julia
* JuliaAcademy: https://juliaacademy.com/
* Github de Jane Herriman: [xorJane](https://github.com/xorJane)

### Uso de Julia
- Desde el REPL (Read-Eval-Print-Loop): `$julia`
- Invocando  `IJulia` (Interface de Python interactivo con kernel de Julia): `$ ipython notebook --profile julia`
- Dentro de un Ambiente de Desarrollo integrado, por ejemplo LightTable + Jewel, Juno, Jupyter, Julia Studio, JuliaPro, Colab, Pluto

## Sintáxis básica, variables y tipos de datos

 ### Variables y cálculos aritméticos

In [1]:
3

3

In [2]:
3 + 2

5

In [3]:
3 * 5 

15

In [4]:
3 - 1; #Ejecución silenciosa

### Modos de REPL

In [5]:
? pwd # ask for help

search: pwd powermod



```
pwd() -> AbstractString
```

Get the current working directory.

# Examples

```julia-repl
julia> pwd()
"/home/JuliaUser"

julia> cd("/home/JuliaUser/Projects/julia")

julia> pwd()
"/home/JuliaUser/Projects/julia"
```


In [6]:
pwd() # shows current working directory

"/home/oscar/Documentos/2021/unam/iimas/colaboracion/saul-tec/tallerJulia/repojulia"

`;` cambia al prompt del shell para ejecutar comandos 

In [7]:
; ls

img
IntroJulia.zip
S1-IntroJulia.ipynb
S2-IntroJulia.ipynb
S3-ObjetosEstructuras.ipynb
S4-JuliaEsRapido.ipynb
S5-CodigoEficiente.ipynb
S6-OtrasFuncionalidadesJulia.ipynb
S7-EjemploNumerico.ipynb
S8-OperacionesVectorizadas.ipynb


In [8]:
x = 3

3

Podemos ingresar en el código notación de Latex, usando sustitución con TAB:  `\alpha<TAB>`

In [10]:
α

LoadError: UndefVarError: α not defined

In [9]:
β

LoadError: UndefVarError: β not defined

In [11]:
α = 3

3

In [12]:
ϵ = 10

10

In [13]:
print("α = ", α)

α = 3

In [14]:
😺 = "michis!!"

"michis!!"

In [15]:
😺

"michis!!"

Para obtener el gato sonriente se hace:

`\:smi + <TAB> --> select with arrows + <ENTER> + <TAB> + <ENTER>` 

### Sustitución de variables
Los valores de las variables pueden ser sustituidos por cadenas de caracteres de una manera sencilla usando el operador `$`

In [16]:
name = "Oscar"
greeting = "Hello, $name"
println(greeting)

Hello, Oscar


In [17]:
μ = 3
println("The sine of $μ is $(sin(μ))")

The sine of 3 is 0.1411200080598672


### Operadores matemáticos

In [ ]:
suma = 3 + 7

In [ ]:
diferencia = 10 - 3

In [ ]:
producto = 3 * 2

In [ ]:
division = 10 / 10

In [ ]:
division2 = div(5, 2)

In [ ]:
potencia = 2 ^ 3

In [ ]:
modulo = 10 % 3

###  Tipos de datos numéricos

Julia contiene un amplio conjunto de tipos de datos:
- Los tipos de datos numéricos pueden tener diferente precisión
- Actualmente, al realizar cálculos aritméticos el tipo de dato resultante es promovido al tipo de dato del equipo de cómputo.
- Al escribir `Float<TAB>` o `Int<TAB>` resultara en una lista desplegable de tipos a elegir.

In [ ]:
Float

In [ ]:
Int

In [18]:
a = Int8(1)
b = Int8(2)
a + b

3

In [19]:
typeof(ans)

Int8

In [20]:
a = Int(1e5)

100000

In [21]:
typeof(a)

Int64

In [22]:
typeof(3 * a)

Int64

Julia esta diseñado de tal forma que provee una jerarquía de tipos de datos la cual define conjuntos y subconjuntos de tipos:

In [23]:
a = 5

5

In [24]:
typeof(a)

Int64

In [25]:
supertype(Int64)

Signed

In [26]:
supertype(Signed)

Integer

In [27]:
supertype(Integer)

Real

In [28]:
subtypes(Real)

4-element Array{Any,1}:
 AbstractFloat
 AbstractIrrational
 Integer
 Rational

In [29]:
subtypes(Integer)

3-element Array{Any,1}:
 Bool
 Signed
 Unsigned

In [30]:
subtypes(Signed)

6-element Array{Any,1}:
 BigInt
 Int128
 Int16
 Int32
 Int64
 Int8

Bajo esta jerarquía de tipos se pueden caracterizar dos grupos de datos:
- Dato **Abstracto** es algo como `Real`
- Dato **Concreto** es algo como `Int64`


In [33]:
isconcretetype(Float64)

true

In [34]:
@show isconcretetype(Real);

isconcretetype(Real) = false


In [35]:
@show isabstracttype(Real);

isabstracttype(Real) = true


El siguiente código muestra la jerarquía de tipos de datos de Julia

In [36]:
function _show_subtype_tree(mytype, printlevel)
    allsubtypes = subtypes(mytype)
    for cursubtype in allsubtypes
        print("\t"^printlevel)
        println("|___",cursubtype)
        printlevel += 1
        _show_subtype_tree(cursubtype, printlevel)
        printlevel -= 1
    end
end
function show_type_tree(T)
    println(T)
    _show_subtype_tree(T,0)
end
show_type_tree(Number)

Number
|___Complex
|___Real
	|___AbstractFloat
		|___BigFloat
		|___Float16
		|___Float32
		|___Float64
	|___AbstractIrrational
		|___Irrational
	|___Integer
		|___Bool
		|___Signed
			|___BigInt
			|___Int128
			|___Int16
			|___Int32
			|___Int64
			|___Int8
		|___Unsigned
			|___UInt128
			|___UInt16
			|___UInt32
			|___UInt64
			|___UInt8
	|___Rational


### Aritmética de precisión arbitraria
Es posible obtener enteros o flotantes de precisión arbitrario por medio de los tipos `BigInt` y `BigFloat`.
La función `Big` convierte un número a el correspontiente tipo `Big`. Julia envuelve (wraps) la biblioteca *GNU Multiple Precision Arithmetic* [GMP](https://gmplib.org/)

In [37]:
10

10

In [38]:
typeof(10)

Int64

In [39]:
big(10)

10

In [40]:
typeof(ans)

BigInt

In [41]:
10^5

100000

In [42]:
10^10

10000000000

In [43]:
10^15 

1000000000000000

In [44]:
10^19 # error

-8446744073709551616

In [45]:
bten = big(10)

10

In [46]:
bten ^ 19

10000000000000000000

In [47]:
typeof(ans)

BigInt

In [48]:
typemax(Int64)

9223372036854775807

In [49]:
typemin(Int64)

-9223372036854775808

### Números complejos
Los números complejos utilizan `im` para la parte imaginaria

In [50]:
a = 7
c = (1 + 3.5im) * a

7.0 + 24.5im

In [51]:
typeof(c)

Complex{Float64}

In [52]:
c.re, c.im

(7.0, 24.5)

In [ ]:
c.re

In [53]:
conj(c) # conj is a funciton that returns the conjugate of a complex

7.0 - 24.5im

### Números racionales
Los números racionales puden ser construidos en Julia al usar el operador `//`

In [54]:
3//4

3//4

In [55]:
typeof(ans)

Rational{Int64}

In [56]:
3//4 + 5//6 

19//12

### Cadenas

In [64]:
s1 = "Esto es un string.""

LoadError: syntax: cannot juxtapose string literal

In [58]:
s2 = """Esto es un string."""

"Esto es un string."

In [59]:
"Aquí hay un "error" porque esto es un tanto ca'nijo"

LoadError: syntax: cannot juxtapose string literal

In [60]:
"""Aquí no hay un "error" porque esto es lo ca'nijo se resolvió"""

"Aquí no hay un \"error\" porque esto es lo ca'nijo se resolvió"

In [61]:
""" Esto es una multi-string
multi-string
multi-string
"""

" Esto es una multi-string\nmulti-string\nmulti-string\n"

**Nota:** Las comillas simples ''denotan un caracter, no una cadena. 

In [65]:
typeof('a')

Char

In [66]:
typeof("a")

String

### Concatenación de cadenas

In [67]:
nombre = "Julia "
apellido =  "Programming"

"Programming"

In [68]:
# usando la función string
string(nombre, apellido)

"Julia Programming"

In [69]:
# usando el operador *
nombre * apellido

"Julia Programming"

Una cadena puede repetirse usando la función `repeat()`, o con los operadores `^` y `*`.

In [70]:
repeat(nombre, 5)

"Julia Julia Julia Julia Julia "

In [71]:
nombre ^ 5

"Julia Julia Julia Julia Julia "

In [72]:
nombre * nombre

"Julia Julia "

## Control de flujo

### Condicionales

La sintáxis para una expresión condicional incluye la palabra reservada `if` y es:
```julia
if *condicion1*
    *opcion 1*
elseif *condicion 2*
    *opcion 2*
else
    *opcion 3*
end
    ```

**Ejercicio:**

Implementemos el tes **fizzbuzz**: Dado un número N, escribir **fizz** si es divisible por 3, **buzz** si es divisible por 5 y **fizzbuzz** si es divisible entre ambos.

De otro modo escribir el número tal cual. 

In [ ]:
N = 7

In [ ]:
if (N % 3 == 0) && isequal(N % 5, 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
   println("Buzz")
else
    println(N)
end

La función `isequal()` es equivalente al operador `==`.

Una forma alternativa de escribir un condicional es por medio de **operadores ternarios**:
```julia
a ? b : c
```
lo que equivale a:
```julia
if a
    b
else
    c
end
```



In [ ]:
x = 3
y = 100

In [ ]:
(x > y) ? x : y

### Short-circuit 

El operador `&` hace la evaluación de dos expresiones booleanas por medio de la operación `AND`. El operador `&&` hace la misma evaluación pero en caso que la primera evaluación sea `false` no hace la segunda evaluación. 

In [ ]:
# operador para AND
false & true

In [ ]:
# short-circuit operator para AND
false && true

In [ ]:
false && (println("Hola"); true)

In [ ]:
true && (println("Hola"); false)

Por otra parte, el operador `&&` no requiere que la segunda expresión devuelva el valor de `true` o `false`, veamos un ejemplo:

In [ ]:
x = 5
(x > 0) && error("x no puede ser mayor que 0")

In [ ]:
(x < 0) && (error("x no puede ser mayor que 0"); true)

De forma similar, el operador `||` es utilizado para hacer la evaluación de corto circuito de la operación `OR`. Dado un `true` en la primera expresión no se evalúa la segunda.

In [73]:
# operador para OR
true | false

true

In [78]:
# short circuit operador para OR 
true || false

true

In [75]:
true || println("hola")

true

In [77]:
false || println("hola")

hola


### Ciclo While 

La sintáxis para un ciclo `while` es:
```julia
while *condition*
    *loop body*
end
    ```

In [79]:
n = 0
while n < 10
    n += 1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

In [80]:
misamigos = ["marco", "raul", "hector", "victor"]

i = 1
while i <= length(misamigos)
    amigo = misamigos[i]
    println("Hola $amigo, ¿qué tal estás?")
    i += 1
end

Hola marco, ¿qué tal estás?
Hola raul, ¿qué tal estás?
Hola hector, ¿qué tal estás?
Hola victor, ¿qué tal estás?


### Ciclo For 

La sintáxis para un ciclo `for` es:
```julia
for *var* in *loop iterable*
    *loop body*
end
    ```

In [81]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [82]:
myfriends = ["Carlos", "Raul", "Edmundo", "Giovanni", "Fabian"]
for name in myfriends
    println("Hola $name, ¿qué tal?")
end

Hola Carlos, ¿qué tal?
Hola Raul, ¿qué tal?
Hola Edmundo, ¿qué tal?
Hola Giovanni, ¿qué tal?
Hola Fabian, ¿qué tal?


## Estructuras de datos

Las estructuras de datos funcionan como colectores de elementos, las estructuras básicas son:
* **Tuplas:** ordenadas, inmutables
* **Diccionarios:** desordenadas (*unordered*), mutables, similares a las _hash tables_ 
* **Arreglos:** ordenadas, mutables

### Tuplas

Se construyen encerrando entre `()` una colección ordenada de elementos.

La sintaxis es:

   `(item1, item2, ...)`

Las tuplas son inmutables. Una vez que son creadas no pueden ser modificadas.

In [83]:
mismascotas = ("alpha", "yanina", "renata")

("alpha", "yanina", "renata")

In [84]:
# indexado
mismascotas[1]

"alpha"

In [85]:
mismascotas[2]

"yanina"

In [86]:
# error
mismascotas[0]

LoadError: BoundsError: attempt to access ("alpha", "yanina", "renata")
  at index [0]

**Nota:** El indexado en Julia inicia en 1

In [87]:
mismascotas[1] = "camaleón"

LoadError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

Las tuplas son **objetos inmutables**, una vez que son creadas no pueden ser modificadas.

### Named Tuples

Es un nuevo tipo de tupla implementado en la versión 1.0. Cada elemento de la tupla tiene un nombre al cual se le asigna un valor.

La sintaxis de este tipo de tupla es:

    `(name1 = item1, name2 = item2, ...)`.

In [88]:
mismascotas_nt = (perro = "alpha", gato = "yanina", tortuga = "renata")

(perro = "alpha", gato = "yanina", tortuga = "renata")

In [89]:
typeof(mismascotas_nt)

NamedTuple{(:perro, :gato, :tortuga),Tuple{String,String,String}}

In [90]:
# recupera elemento por índice
mismascotas_nt[1]

"alpha"

In [91]:
# recupera elemento por el nombre
mismascotas_nt.gato

"yanina"

### Diccionarios

Usualmente los diccionarios se utilizan cuando se tienen dos conjuntos de datos los cuales están interrelacionados. Los diccionarios se construyen usando la función `Dict()`, la inicialización puede ser un diccionario vacío. La sintaxis es:

`Dict(key1 => value1, key2 =>value2, ...)`

Un ejemplo del uso de un diccionario es una lista de contactos que asocia nombre con números telefónicos:

In [92]:
mycontacts = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String,String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [93]:
# inicializa un diccionario vacío
mydict = Dict()

Dict{Any,Any}()

In [94]:
# indexado por llave
mycontacts["Jenny"]

"867-5309"

In [95]:
# agrega un elemento al diccionario
mycontacts["Chloe"] = "321-7562"

"321-7562"

In [96]:
mycontacts

Dict{String,String} with 3 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"
  "Chloe"        => "321-7562"

Para eliminar un elemento del diccionario se utiliza la función `pop!`

In [97]:
pop!(mycontacts, "Ghostbusters")

"555-2368"

In [98]:
mycontacts

Dict{String,String} with 2 entries:
  "Jenny" => "867-5309"
  "Chloe" => "321-7562"

## Arreglos

Un arreglo _Array_ es una estructura de datos que equivale a las listas de Python y a los arreglos de `numpy`.

En Julia los arreglos son estructuras **modificables** (_mutable_) que contiene colecciones de datos ordenados. La construcción de un Array se hace por medio del uso de `[ ]`.

La sintaxis es:

`[item1, item2, ...]`

In [99]:
myfriends = ["Julio", "Marco", "Victor", "Cesar", "Manuel"]

5-element Array{String,1}:
 "Julio"
 "Marco"
 "Victor"
 "Cesar"
 "Manuel"

`Array{String, 1}` denota que se trata de un arreglo unidimensional con tipo de datos `string`.

In [100]:
fibonacci  = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [101]:
myarray = [1, 1, 2, 3, "cinco", "ocho", "trece"]

7-element Array{Any,1}:
 1
 1
 2
 3
  "cinco"
  "ocho"
  "trece"

In [102]:
# indexado del array
myfriends[2]

"Marco"

In [103]:
# modifica el array usando el índice
myfriends[4] = "Héctor"

"Héctor"

In [104]:
myfriends

5-element Array{String,1}:
 "Julio"
 "Marco"
 "Victor"
 "Héctor"
 "Manuel"

**Nota:** El indexado en Julia inicia en 1 (_1-based indexing_) que difiere de otros lenguajes como Python.

In [105]:
l = [3, 4, 5]

3-element Array{Int64,1}:
 3
 4
 5

In [106]:
typeof(l)

Array{Int64,1}

In [107]:
l = [3, 4, 7.5] # promoting to float

3-element Array{Float64,1}:
 3.0
 4.0
 7.5

In [108]:
l = [3.,"hello"]

2-element Array{Any,1}:
 3.0
  "hello"

In [109]:
l = [3.,'a']

2-element Array{Any,1}:
 3.0
  'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [110]:
l = [3., 4, "hello", [3, 4]]

4-element Array{Any,1}:
 3.0
 4
  "hello"
  [3, 4]

La agregación y eleminación de elementos de un array se realiza por medio de las funciones `push!` y  `pop!` respectivamente.

In [111]:
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [112]:
# agrega 21 al final del array
push!(fibonacci, 21 )
fibonacci

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

In [113]:
# remueve 21, el último elemento del array.
pop!(fibonacci)
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

Los ejemplos anteriores son arreglos de escalares, sin embargo, los arreglos pueden tener un número arbitrario de dimensiones y pueden almacenar otros arrays.


In [114]:
favoritos = [["chocolate", "almendras", "pistache"], ["gato", "perro", "patito"]]

2-element Array{Array{String,1},1}:
 ["chocolate", "almendras", "pistache"]
 ["gato", "perro", "patito"]

In [115]:
numeros = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [116]:
numeros = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

### Indexado
Los índices de los arreglos de Julia comienzan en 1, a diferencia de Python (inician en 0).

In [117]:
l = [3, 4, "hello"]

3-element Array{Any,1}:
 3
 4
  "hello"

In [118]:
l[1] 

3

In [119]:
l[1:2]

2-element Array{Any,1}:
 3
 4

In [120]:
l[2:end] # use 'end' explicitly

2-element Array{Any,1}:
 4
  "hello"

In [121]:
l[1:end-1]

2-element Array{Any,1}:
 3
 4

In [122]:
l[-1]

LoadError: BoundsError: attempt to access 3-element Array{Any,1} at index [-1]

Los arreglos de Julia, como las listas de Python (aunque diferentes a los arreglos de `numpy`) son dinámicos. Sin embargo, la sintaxis es un poco diferente a la de Python; para agregar un elemento al final de un arreglo, se requiere escribir:

Julia `Arrays`, like Python lists, but unlike `numpy` arrays, are dynamic. However, the syntax is rather different from Python -- to add an element at hte end of the list, we write:

In [123]:
l = [3, 4, 5]

3-element Array{Int64,1}:
 3
 4
 5

In [124]:
l = [3, 4, 5]
push!(l,7)

4-element Array{Int64,1}:
 3
 4
 5
 7

In [125]:
l

4-element Array{Int64,1}:
 3
 4
 5
 7

In [126]:
l = [3, 4, 5]
l + l

3-element Array{Int64,1}:
  6
  8
 10

Los `arrays` de Julia son objetos, sin embargo, a diferencia de Python, no tienen métodos implementados. La función `push()` más el signo de admiración `!` denota una convención en Julia que significa que esta función modificará a su argumento. En el ejemplo previo, el objeto `l` se modifica al incluir al final del arreglo el valor `7` 

In [127]:
push!

push! (generic function with 25 methods)

In [128]:
methods(push!)

# 25 methods for generic function "push!":
[1] push!(pool::Distributed.WorkerPool, w::Int64) in Distributed at /home/oscar/julia-1.5.3/share/julia/stdlib/v1.5/Distributed/src/workerpool.jl:152
[2] push!(entry::Pkg.Resolve.ResolveLogEntry, reason::Tuple{Union{Nothing, Pkg.Resolve.ResolveLogEntry},String}) in Pkg.Resolve at /home/oscar/julia-1.5.3/share/julia/stdlib/v1.5/Pkg/src/Resolve/graphtype.jl:28
[3] push!(entry::Pkg.Resolve.ResolveLogEntry, reason::Tuple{Union{Nothing, Pkg.Resolve.ResolveLogEntry},String}, to_journal::Bool) in Pkg.Resolve at /home/oscar/julia-1.5.3/share/julia/stdlib/v1.5/Pkg/src/Resolve/graphtype.jl:28
[4] push!(a::Array{Any,1}, item) in Base at array.jl:940
[5] push!(::Base.Nowhere, ::Any) in Base at array.jl:1347
[6] push!(::Base.EnvDict, kv::Pair{var"#s828",B} where B where var"#s828"<:AbstractString) in Base at env.jl:87
[7] push!(md::Markdown.MD, x) in Markdown at /home/oscar/julia-1.5.3/share/julia/stdlib/v1.5/Markdown/src/parse/parse.jl:23
[8] push!(B::BitArray{1}, item) in Base at bitarray.jl:737
[9] push!(c::CompositeException, ex) in Base at task.jl:42
[10] push!(s::BitSet, n::Integer) in Base at bitset.jl:273
[11] push!(s::BitSet, ns::Integer...) in Base at bitset.jl:275
[12] push!(a::Array{T,1}, item) where T in Base at array.jl:932
[13] push!(a::AbstractArray{T,1} where T, iter...) in Base at array.jl:982
[14] push!(t::AbstractDict, p::Pair) in Base at abstractdict.jl:510
[15] push!(t::AbstractDict, p::Pair, q::Pair) in Base at abstractdict.jl:511
[16] push!(t::AbstractDict, p::Pair, q::Pair, r::Pair...) in Base at abstractdict.jl:512
[17] push!(s::Base.IdSet, x) in Base at idset.jl:20
[18] push!(s::Set, x) in Base at set.jl:57
[19] push!(q::Base.InvasiveLinkedList{Base.LinkedListItem{T}}, val::T) where T in Base at linked_list.jl:137
[20] push!(q::Base.InvasiveLinkedList{T}, val::T) where T in Base at linked_list.jl:52
[21] push!(c::Channel, v) in Base at channels.jl:349
[22] push!(W::Base.InvasiveLinkedListSynchronized{T}, t::T) where T in Base at task.jl:468
[23] push!(pool::Distributed.AbstractWorkerPool, w::Int64) in Distributed at /home/oscar/julia-1.5.3/share/julia/stdlib/v1.5/Distributed/src/workerpool.jl:161
[24] push!(A, a, b) in Base at abstractarray.jl:2252
[25] push!(A, a, b, c...) in Base at abstractarray.jl:2253

Dando click al link, podemos enlazarnos al repositorio en github donde está el código del método

In [129]:
append!(l, [10, 11, 12])

6-element Array{Int64,1}:
  3
  4
  5
 10
 11
 12

Los siguientes arreglos 2D y 3D son generados con usando números aleatorios:

In [130]:
rand(4, 3)

4×3 Array{Float64,2}:
 0.248507  0.989697  0.84182
 0.213865  0.703109  0.829025
 0.550501  0.400473  0.309024
 0.269044  0.368582  0.723594

In [131]:
rand(4, 3, 2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.674338    0.669101   0.660027
 0.522593    0.0370932  0.332194
 0.733272    0.290698   0.728368
 0.00465543  0.675434   0.0823722

[:, :, 2] =
 0.180276  0.996748  0.442185
 0.66977   0.890155  0.680381
 0.258791  0.101047  0.550122
 0.915238  0.916575  0.126205

`rand()` genera arreglos con valores aleatorios dentro del rango `[0,1]`

Es posible agregar el rango de elementos a la construcción de un arreglo aleatorio.

In [132]:
rand(-10:10, 4, 3)

4×3 Array{Int64,2}:
 6   -5  -10
 8  -10   -2
 7    9    6
 4    7   -3

### Copia de arreglos

In [133]:
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [134]:
misnumeros = fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [135]:
misnumeros[1] = 50
misnumeros

7-element Array{Int64,1}:
 50
  1
  2
  3
  5
  8
 13

In [136]:
fibonacci

7-element Array{Int64,1}:
 50
  1
  2
  3
  5
  8
 13

Editar la copia de un arreglo modifica el original, esto es que sólo se asigna un nuevo nombre a un arreglo existente .`fibonacci` es modificado al asignar valores a `misnumeros`.

No se hace una copia de `fibonacci`, tan solo se ha creado un nuevo acceso a este arreglo por medio de `misnumeros`. Una copia de un arreglo se hace por medio de la función `copy()`.

In [137]:
fibonacci[1] = 1
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [138]:
newnumeros = copy(fibonacci)
newnumeros

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [139]:
newnumeros[1] = 50
newnumeros

7-element Array{Int64,1}:
 50
  1
  2
  3
  5
  8
 13

In [140]:
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

### Comprehensión de arreglos

Por medio de un ciclo `for` se va a crear una tabla de suma (_adition table_) donde cada entrada es la suma de sus correspondientes índices de renglón y columna.  

In [141]:
m,n = 5,5
A = fill(0, (m,n))

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [142]:
for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

De forma equivalente podemos hacer:

In [143]:
m,n = 5,5
B = fill(0, (m,n))

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [144]:
for i in 1:m, j in 1:n
        B[i,j] = i + j
end
B

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Crear esta tabla al más puro estilo Julia es por medio del uso de **comprehensión de arreglos**:

In [145]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Esta comprehensión de arreglos es equivalente a la _comprehensión de listas_ de python

In [146]:
[x for x in 1:15]

15-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

## Operaciones con arreglos

Julia provee diversas operaciones predefinidas para operar sobre arreglos que resultan muy útiles.

In [148]:
a = [1.1, 2.2, 3.3]
b = [4.4, 5.5, 6.6]

3-element Array{Float64,1}:
 4.4
 5.5
 6.6

In [149]:
a + b

3-element Array{Float64,1}:
 5.5
 7.7
 9.899999999999999

In [150]:
3.5 * a

3-element Array{Float64,1}:
  3.8500000000000005
  7.700000000000001
 11.549999999999999

Sin embargo, los operadores, en general, no operan _elemento a elemento_ (como sucedería en `numpy`):

In [151]:
a * b

LoadError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  *(!Matched::LinearAlgebra.Adjoint{var"#s828",var"#s8281"} where var"#s8281"<:(AbstractArray{T,1} where T) where var"#s828"<:Number, ::AbstractArray{var"#s827",1} where var"#s827"<:Number) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:283
  *(!Matched::LinearAlgebra.Transpose{T,var"#s828"} where var"#s828"<:(AbstractArray{T,1} where T), ::AbstractArray{T,1}) where T<:Real at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:284
  ...

No obstante, las operaciones _elemento a elemento_ pueden hacerse tipo sintaxis de _Matlab_ anteponiendo el símbolo `.` al operador:

In [152]:
a.*b

3-element Array{Float64,1}:
  4.840000000000001
 12.100000000000001
 21.779999999999998

A partir de la Julia v1.0 algunas funciones cambiaron al paquete `LinearAlgebra`

In [154]:
#Pkg.add("LinearAlgebra")
using LinearAlgebra

In [155]:
dot(a,b)

38.72

In [156]:
cross(a,b)

3-element Array{Float64,1}:
 -3.629999999999999
  7.26
 -3.630000000000001

In [157]:
?cross() #Documentación de cross()

```
cross(x, y)
×(x,y)
```

Compute the cross product of two 3-vectors.

# Examples

```jldoctest
julia> a = [0;1;0]
3-element Array{Int64,1}:
 0
 1
 0

julia> b = [0;0;1]
3-element Array{Int64,1}:
 0
 0
 1

julia> cross(a,b)
3-element Array{Int64,1}:
 1
 0
 0
```


In [158]:
norm(a)

4.115823125451335

In [159]:
?norm()

```
norm(A, p::Real=2)
```

For any iterable container `A` (including arrays of any dimension) of numbers (or any element type for which `norm` is defined), compute the `p`-norm (defaulting to `p=2`) as if `A` were a vector of the corresponding length.

The `p`-norm is defined as

$$
\|A\|_p = \left( \sum_{i=1}^n | a_i | ^p \right)^{1/p}
$$

with $a_i$ the entries of $A$, $| a_i |$ the [`norm`](@ref) of $a_i$, and $n$ the length of $A$. Since the `p`-norm is computed using the [`norm`](@ref)s of the entries of `A`, the `p`-norm of a vector of vectors is not compatible with the interpretation of it as a block vector in general if `p != 2`.

`p` can assume any numeric value (even though not all values produce a mathematically valid vector norm). In particular, `norm(A, Inf)` returns the largest value in `abs.(A)`, whereas `norm(A, -Inf)` returns the smallest. If `A` is a matrix and `p=2`, then this is equivalent to the Frobenius norm.

The second argument `p` is not necessarily a part of the interface for `norm`, i.e. a custom type may only implement `norm(A)` without second argument.

Use [`opnorm`](@ref) to compute the operator norm of a matrix.

# Examples

```jldoctest
julia> v = [3, -2, 6]
3-element Array{Int64,1}:
  3
 -2
  6

julia> norm(v)
7.0

julia> norm(v, 1)
11.0

julia> norm(v, Inf)
6.0

julia> norm([1 2 3; 4 5 6; 7 8 9])
16.881943016134134

julia> norm([1 2 3 4 5 6 7 8 9])
16.881943016134134

julia> norm(1:9)
16.881943016134134

julia> norm(hcat(v,v), 1) == norm(vcat(v,v), 1) != norm([v,v], 1)
true

julia> norm(hcat(v,v), 2) == norm(vcat(v,v), 2) == norm([v,v], 2)
true

julia> norm(hcat(v,v), Inf) == norm(vcat(v,v), Inf) != norm([v,v], Inf)
true
```

---

```
norm(x::Number, p::Real=2)
```

For numbers, return $\left( |x|^p \right)^{1/p}$.

# Examples

```jldoctest
julia> norm(2, 1)
2.0

julia> norm(-2, 1)
2.0

julia> norm(2, 2)
2.0

julia> norm(-2, 2)
2.0

julia> norm(2, Inf)
2.0

julia> norm(-2, Inf)
2.0
```


In [160]:
a # vector columna

3-element Array{Float64,1}:
 1.1
 2.2
 3.3

In [161]:
transpose(a) # vector renglón

1×3 Transpose{Float64,Array{Float64,1}}:
 1.1  2.2  3.3

In [162]:
a' # row vector

1×3 Adjoint{Float64,Array{Float64,1}}:
 1.1  2.2  3.3

In [163]:
a

3-element Array{Float64,1}:
 1.1
 2.2
 3.3

In [164]:
M = [1 2 3 4] # spaces distribute as row

1×4 Array{Int64,2}:
 1  2  3  4

In [165]:
M = [1, 2, 3, 4] # the comma distribute as column

4-element Array{Int64,1}:
 1
 2
 3
 4

In [166]:
M = [[1, 2], [3, 4]] # brackets works as array

2-element Array{Array{Int64,1},1}:
 [1, 2]
 [3, 4]

In [167]:
M = reshape([1, 2, 3, 4], (2,2))

2×2 Array{Int64,2}:
 1  3
 2  4

In [168]:
M = [[2, 1]; [3, 1]]

4-element Array{Int64,1}:
 2
 1
 3
 1

In [169]:
 M = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [170]:
M = [1:8;] # semicolon ; is important ¿por qué?

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [171]:
M = [1:8;10]

9-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
 10

In [172]:
typeof([1:8;])

Array{Int64,1}

In [173]:
M = collect(1:8)

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [174]:
typeof(collect(1:8))

Array{Int64,1}

In [175]:
? collect()

```
collect(element_type, collection)
```

Return an `Array` with the given element type of all items in a collection or iterable. The result has the same shape and number of dimensions as `collection`.

# Examples

```jldoctest
julia> collect(Float64, 1:2:5)
3-element Array{Float64,1}:
 1.0
 3.0
 5.0
```

---

```
collect(collection)
```

Return an `Array` of all items in a collection or iterator. For dictionaries, returns `Pair{KeyType, ValType}`. If the argument is array-like or is an iterator with the [`HasShape`](@ref IteratorSize) trait, the result will have the same shape and number of dimensions as the argument.

# Examples

```jldoctest
julia> collect(1:2:13)
7-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13
```


In [176]:
M = reshape([1:8;], (2,2,2))

2×2×2 Array{Int64,3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

In [177]:
a, b

([1.1, 2.2, 3.3], [4.4, 5.5, 6.6])

In [178]:
a ⋅ b # \cdot + <TAB> dot product

38.72

In [ ]:
a × b # \times + <TAB> cross product

## Ejercicio

Implementarla el método Babilonio para calcular la raíz cuadrada de un número entero positivo $y$, por medio de la iteración: $$ x_{n+1}= \frac{1}{2}\left( x_n + \frac{y}{x_n} \right)$$

Una implementación de la solución puede ser:

In [ ]:
y = 100
xn = 1
for i = 1:10
    xnew = (1/2)*(xn + y/xn)
    xn = xnew
    println("$xnew\t")
end
println()
print("La raíz cuadrada de $y is: $xn")